# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  INPUT_DIR: input_dir
  OUTPUT_DIR: output_dir
  REMOVED_NOISE_DIR: removed_noise
  DECLIPPED_DIR: declipped_dir
  FRAMES_PER_BUFFER: 3200
  CHANNELS: 1 
  RATE: 16000
  SECONDS: 5